//! Built-in model definitions loaded from `models.json`.
//!
//! The [`register_built_in_models`] function loads a curated set of models
//! (generated from [models.dev](https://models.dev)) into a
//! [`DefaultModelRegistry`](crate::DefaultModelRegistry) at runtime. The model
//! data is embedded in the binary via `include_str!` so no runtime network
//! access is needed.

use crate::DefaultModelRegistry;
use ameli_ai::types::Model;

#[cfg(test)]
use crate::ModelRegistry;

/// Register all built-in models into the given registry.
///
/// The models are loaded from a compiled-in JSON file that was generated by
/// the `generate-models` binary (see `src/bin/generate-models.rs`).
///
/// # Errors
///
/// If the embedded JSON cannot be deserialized, a warning is logged and the
/// function returns without panicking. Downstream applications can still
/// register models manually.
pub fn register_built_in_models(registry: &DefaultModelRegistry) {
    let data = include_str!("models.json");
    match serde_json::from_str::<Vec<Model>>(data) {
        Ok(models) => {
            let count = models.len();
            for model in models {
                registry.register(model);
            }
            tracing::info!("Loaded {count} built-in models into registry");
        }
        Err(e) => {
            tracing::warn!("Failed to load built-in models: {e}");
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn register_built_in_models_loads_models() {
        let registry = DefaultModelRegistry::new();
        register_built_in_models(&registry);

        let all = registry.all_models();
        assert!(!all.is_empty(), "Built-in models should be non-empty");

        // Check that we have multiple providers
        let providers = registry.providers();
        assert!(
            providers.len() >= 10,
            "Expected at least 10 providers, got {}: {providers:?}",
            providers.len()
        );
    }

    #[test]
    fn register_built_in_models_specific_model_findable() {
        let registry = DefaultModelRegistry::new();
        register_built_in_models(&registry);

        // Look up a known Groq model
        let found = registry.get_model("groq", "llama-3.3-70b-versatile");
        assert!(
            found.is_ok(),
            "Expected to find groq/llama-3.3-70b-versatile, got: {:?}",
            found
        );
        let model = found.unwrap();
        assert_eq!(model.api, "openai-completions");
        assert_eq!(model.provider, "groq");
    }

    #[test]
    fn built_in_models_have_compat() {
        let registry = DefaultModelRegistry::new();
        register_built_in_models(&registry);

        let all = registry.all_models();
        let without_compat: Vec<&Model> = all.iter().filter(|m| m.compat.is_none()).collect();
        assert!(
            without_compat.is_empty(),
            "All built-in models should have compat set, but {} don't: {:?}",
            without_compat.len(),
            without_compat
                .iter()
                .map(|m| format!("{}/{}", m.provider, m.id))
                .collect::<Vec<_>>()
        );
    }
}
