//! Session entry types and context structures.
//!
//! Defines the data model for the session tree: the seven entry variants that
//! make up a session's append-only history, the [`SessionEntry`] tagged enum,
//! and the [`SessionContext`] produced by walking the tree.

use ameli_agent_core::types::AgentMessage;
use ameli_ai::types::MediaContentBlock;
use std::fmt;

// ---------------------------------------------------------------------------
// Session Context
// ---------------------------------------------------------------------------

/// Lightweight model identifier restored from session history.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ModelRef {
    /// Provider name (e.g., `"openai"`, `"anthropic"`).
    pub provider: String,
    /// Model identifier within the provider (e.g., `"gpt-4o"`).
    pub model_id: String,
}

/// The resolved session context produced by walking the session tree.
///
/// Contains the messages to send to the LLM, the current thinking level,
/// and the model selection — all reconstructed from the entry history.
#[derive(Debug, Clone)]
pub struct SessionContext {
    /// Messages in conversation order, ready for the LLM.
    pub messages: Vec<AgentMessage>,
    /// Current thinking/reasoning level.
    pub thinking_level: String,
    /// Current model selection, if any has been recorded.
    pub model: Option<ModelRef>,
}

// ---------------------------------------------------------------------------
// Custom Message Content
// ---------------------------------------------------------------------------

/// Content for a [`CustomMessageEntry`].
///
/// Extensions can inject either plain text or rich content (text + images)
/// into the LLM context.
#[derive(Debug, Clone, PartialEq)]
pub enum CustomMessageContent {
    /// Plain text content.
    Text(String),
    /// Rich content with text and/or image blocks.
    Rich(Vec<MediaContentBlock>),
}

// ---------------------------------------------------------------------------
// Entry Types
// ---------------------------------------------------------------------------

/// A conversation message (user, assistant, or tool result).
#[derive(Debug, Clone)]
pub struct MessageEntry {
    /// Unique entry identifier within the session.
    pub id: String,
    /// Parent entry ID (forms the tree structure). `None` for root entries.
    pub parent_id: Option<String>,
    /// ISO 8601 timestamp.
    pub timestamp: String,
    /// The conversation message.
    pub message: AgentMessage,
}

/// Records a change in the thinking/reasoning level.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ThinkingLevelChangeEntry {
    /// Unique entry identifier.
    pub id: String,
    /// Parent entry ID.
    pub parent_id: Option<String>,
    /// ISO 8601 timestamp.
    pub timestamp: String,
    /// New thinking level (e.g., `"off"`, `"medium"`, `"high"`).
    pub thinking_level: String,
}

/// Records a change in the active model.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ModelChangeEntry {
    /// Unique entry identifier.
    pub id: String,
    /// Parent entry ID.
    pub parent_id: Option<String>,
    /// ISO 8601 timestamp.
    pub timestamp: String,
    /// Provider name.
    pub provider: String,
    /// Model identifier.
    pub model_id: String,
}

/// A compaction summary that replaces older messages with a condensed form.
#[derive(Debug, Clone)]
pub struct CompactionEntry {
    /// Unique entry identifier.
    pub id: String,
    /// Parent entry ID.
    pub parent_id: Option<String>,
    /// ISO 8601 timestamp.
    pub timestamp: String,
    /// LLM-generated summary of the compacted conversation.
    pub summary: String,
    /// ID of the first entry kept after compaction.
    pub first_kept_entry_id: String,
    /// Token count before compaction.
    pub tokens_before: u64,
    /// Extension-specific data (e.g., file tracking, version markers).
    pub details: Option<serde_json::Value>,
    /// `true` if generated by an extension hook rather than built-in compaction.
    pub from_hook: bool,
}

/// A summary of an abandoned branch, kept for LLM context continuity.
#[derive(Debug, Clone)]
pub struct BranchSummaryEntry {
    /// Unique entry identifier.
    pub id: String,
    /// Parent entry ID.
    pub parent_id: Option<String>,
    /// ISO 8601 timestamp.
    pub timestamp: String,
    /// ID of the entry this branch was taken from.
    pub from_id: String,
    /// LLM-readable summary of the abandoned branch.
    pub summary: String,
    /// Extension-specific data (not sent to LLM).
    pub details: Option<serde_json::Value>,
    /// `true` if generated by an extension hook.
    pub from_hook: bool,
}

/// Generic extension state entry. Does NOT participate in LLM context.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CustomEntry {
    /// Unique entry identifier.
    pub id: String,
    /// Parent entry ID.
    pub parent_id: Option<String>,
    /// ISO 8601 timestamp.
    pub timestamp: String,
    /// Extension identifier for filtering on reload.
    pub custom_type: String,
    /// Arbitrary extension-specific data.
    pub data: Option<serde_json::Value>,
}

/// An extension-injected message that participates in LLM context.
#[derive(Debug, Clone)]
pub struct CustomMessageEntry {
    /// Unique entry identifier.
    pub id: String,
    /// Parent entry ID.
    pub parent_id: Option<String>,
    /// ISO 8601 timestamp.
    pub timestamp: String,
    /// Extension identifier for filtering on reload.
    pub custom_type: String,
    /// Message content (plain text or rich blocks).
    pub content: CustomMessageContent,
    /// Whether to display in the UI.
    pub display: bool,
    /// Extension-specific metadata (not sent to LLM).
    pub details: Option<serde_json::Value>,
}

// ---------------------------------------------------------------------------
// SessionEntry Enum
// ---------------------------------------------------------------------------

/// A single entry in the session tree.
///
/// Sessions are append-only trees where each entry has an `id` and
/// `parent_id` forming the tree structure. The active "leaf" tracks the
/// current position. New entries are appended as children of the leaf.
#[derive(Debug, Clone)]
pub enum SessionEntry {
    Message(MessageEntry),
    ThinkingLevelChange(ThinkingLevelChangeEntry),
    ModelChange(ModelChangeEntry),
    Compaction(CompactionEntry),
    BranchSummary(BranchSummaryEntry),
    Custom(CustomEntry),
    CustomMessage(CustomMessageEntry),
}

impl SessionEntry {
    /// Returns the unique identifier for this entry.
    pub fn id(&self) -> &str {
        match self {
            Self::Message(e) => &e.id,
            Self::ThinkingLevelChange(e) => &e.id,
            Self::ModelChange(e) => &e.id,
            Self::Compaction(e) => &e.id,
            Self::BranchSummary(e) => &e.id,
            Self::Custom(e) => &e.id,
            Self::CustomMessage(e) => &e.id,
        }
    }

    /// Returns the parent entry ID, or `None` for root entries.
    pub fn parent_id(&self) -> Option<&str> {
        match self {
            Self::Message(e) => e.parent_id.as_deref(),
            Self::ThinkingLevelChange(e) => e.parent_id.as_deref(),
            Self::ModelChange(e) => e.parent_id.as_deref(),
            Self::Compaction(e) => e.parent_id.as_deref(),
            Self::BranchSummary(e) => e.parent_id.as_deref(),
            Self::Custom(e) => e.parent_id.as_deref(),
            Self::CustomMessage(e) => e.parent_id.as_deref(),
        }
    }

    /// Returns the ISO 8601 timestamp for this entry.
    pub fn timestamp(&self) -> &str {
        match self {
            Self::Message(e) => &e.timestamp,
            Self::ThinkingLevelChange(e) => &e.timestamp,
            Self::ModelChange(e) => &e.timestamp,
            Self::Compaction(e) => &e.timestamp,
            Self::BranchSummary(e) => &e.timestamp,
            Self::Custom(e) => &e.timestamp,
            Self::CustomMessage(e) => &e.timestamp,
        }
    }

    /// Returns the discriminant name for this entry type (e.g., `"message"`,
    /// `"compaction"`).
    pub fn entry_type(&self) -> &'static str {
        match self {
            Self::Message(_) => "message",
            Self::ThinkingLevelChange(_) => "thinking_level_change",
            Self::ModelChange(_) => "model_change",
            Self::Compaction(_) => "compaction",
            Self::BranchSummary(_) => "branch_summary",
            Self::Custom(_) => "custom",
            Self::CustomMessage(_) => "custom_message",
        }
    }
}

impl fmt::Display for SessionEntry {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}({})", self.entry_type(), self.id())
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use ameli_ai::types::TextContent;

    fn test_user_message(text: &str) -> AgentMessage {
        AgentMessage::User(ameli_ai::types::UserMessage::text(text))
    }

    fn test_message_entry(id: &str, parent_id: Option<&str>, text: &str) -> MessageEntry {
        MessageEntry {
            id: id.to_string(),
            parent_id: parent_id.map(String::from),
            timestamp: "2026-01-01T00:00:00Z".to_string(),
            message: test_user_message(text),
        }
    }

    #[test]
    fn entry_accessors_message() {
        let entry = SessionEntry::Message(test_message_entry("abc", None, "hi"));
        assert_eq!(entry.id(), "abc");
        assert!(entry.parent_id().is_none());
        assert_eq!(entry.timestamp(), "2026-01-01T00:00:00Z");
        assert_eq!(entry.entry_type(), "message");
    }

    #[test]
    fn entry_accessors_with_parent() {
        let entry = SessionEntry::ModelChange(ModelChangeEntry {
            id: "def".to_string(),
            parent_id: Some("abc".to_string()),
            timestamp: "2026-01-01T00:00:01Z".to_string(),
            provider: "openai".to_string(),
            model_id: "gpt-4o".to_string(),
        });
        assert_eq!(entry.id(), "def");
        assert_eq!(entry.parent_id(), Some("abc"));
        assert_eq!(entry.entry_type(), "model_change");
    }

    #[test]
    fn entry_display() {
        let entry = SessionEntry::ThinkingLevelChange(ThinkingLevelChangeEntry {
            id: "xyz".to_string(),
            parent_id: None,
            timestamp: "2026-01-01T00:00:00Z".to_string(),
            thinking_level: "high".to_string(),
        });
        assert_eq!(format!("{entry}"), "thinking_level_change(xyz)");
    }

    #[test]
    fn custom_message_content_text() {
        let content = CustomMessageContent::Text("hello".to_string());
        assert_eq!(content, CustomMessageContent::Text("hello".to_string()));
    }

    #[test]
    fn custom_message_content_rich() {
        let content =
            CustomMessageContent::Rich(vec![MediaContentBlock::Text(TextContent::new("rich"))]);
        assert!(matches!(content, CustomMessageContent::Rich(_)));
    }

    #[test]
    fn model_ref_equality() {
        let a = ModelRef {
            provider: "openai".to_string(),
            model_id: "gpt-4o".to_string(),
        };
        let b = ModelRef {
            provider: "openai".to_string(),
            model_id: "gpt-4o".to_string(),
        };
        assert_eq!(a, b);
    }

    #[test]
    fn all_entry_variants_have_distinct_type_names() {
        let entries: Vec<SessionEntry> = vec![
            SessionEntry::Message(test_message_entry("1", None, "a")),
            SessionEntry::ThinkingLevelChange(ThinkingLevelChangeEntry {
                id: "2".to_string(),
                parent_id: None,
                timestamp: String::new(),
                thinking_level: "off".to_string(),
            }),
            SessionEntry::ModelChange(ModelChangeEntry {
                id: "3".to_string(),
                parent_id: None,
                timestamp: String::new(),
                provider: "p".to_string(),
                model_id: "m".to_string(),
            }),
            SessionEntry::Compaction(CompactionEntry {
                id: "4".to_string(),
                parent_id: None,
                timestamp: String::new(),
                summary: "s".to_string(),
                first_kept_entry_id: "1".to_string(),
                tokens_before: 100,
                details: None,
                from_hook: false,
            }),
            SessionEntry::BranchSummary(BranchSummaryEntry {
                id: "5".to_string(),
                parent_id: None,
                timestamp: String::new(),
                from_id: "1".to_string(),
                summary: "s".to_string(),
                details: None,
                from_hook: false,
            }),
            SessionEntry::Custom(CustomEntry {
                id: "6".to_string(),
                parent_id: None,
                timestamp: String::new(),
                custom_type: "test".to_string(),
                data: None,
            }),
            SessionEntry::CustomMessage(CustomMessageEntry {
                id: "7".to_string(),
                parent_id: None,
                timestamp: String::new(),
                custom_type: "test".to_string(),
                content: CustomMessageContent::Text("hi".to_string()),
                display: true,
                details: None,
            }),
        ];

        let type_names: Vec<&str> = entries.iter().map(|e| e.entry_type()).collect();
        let unique: std::collections::HashSet<&str> = type_names.iter().copied().collect();
        assert_eq!(
            unique.len(),
            entries.len(),
            "all entry types should be distinct"
        );
    }
}
